//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTalk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTalk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ////****** Object:  Database [AutoComplete]    Script Date: 11/19/2009 23:45:15 ******/
        ///IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N&apos;AutoComplete&apos;)
        ///BEGIN
        ///CREATE DATABASE [AutoComplete] ON  PRIMARY 
        ///( NAME = N&apos;AutoComplete&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\AutoComplete.mdf&apos; , SIZE = 16384KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        /// LOG ON 
        ///( NAME = N&apos;AutoComplete_log&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GenerateAutoCompleteDatabase {
            get {
                return ResourceManager.GetString("GenerateAutoCompleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///osql -S S071241\SQLEXPRESS -d AUTOCOMPLETE -E -i C:\spraakprogramma\SimpleTalk\Database\GenerateAutoCompleteDatabase.sql
        ///ECHO Het bestand is uitgevoerd. 
        ///ECHO -
        ///PAUSE.
        /// </summary>
        internal static string GenerateAutoCompleteDatabase1 {
            get {
                return ResourceManager.GetString("GenerateAutoCompleteDatabase1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ja {
            get {
                return ResourceManager.GetStream("Ja", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Nee {
            get {
                return ResourceManager.GetStream("Nee", resourceCulture);
            }
        }
    }
}
